resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3/snapshot.yaml
compiler: ghc-8.6.5
allow-newer: true

packages:
  - contra-tracer
  - tracer-transformers
  - iohk-monitoring
  - plugins/backend-aggregation
  - plugins/backend-editor
  - plugins/backend-ekg
  - plugins/backend-graylog
  - plugins/backend-monitoring
  - plugins/backend-trace-acceptor
  - plugins/backend-trace-forwarder
  - plugins/scribe-systemd
  - examples

extra-deps:
  - network-3.1.1.1
  - time-units-1.0.0
  - libsystemd-journal-1.4.4
  - katip-0.8.4.0
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: d8aac6f6a40b4311d5824a9151690178c430302d
    subdirs:
        - Win32-network

nix:
  shell-file: nix/stack-shell.nix
